# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
before_install:
  - julia -e 'Pkg.clone("PyLCM")'
  - julia -e 'Pkg.checkout("PyLCM")'
  - julia -e 'Pkg.build("PyLCM")'
notifications:
  email: false
