# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
branches:
  only: master
matrix:
  include:
    - os: linux
      julia: 0.5
    - os: linux
      julia: 0.6
    - os: osx
      julia: 0.5
      env: PYTHON="/usr/local/bin/python"
    - os: osx
      julia: 0.6
      env: PYTHON="/usr/local/bin/python"
  allow_failures:
    - julia: 0.6
notifications:
  email: false
