# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 0.6
  - 1.0
  - nightly
dist: trusty
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7-"; using Pkg; else; cd(Pkg.dir("BotCoreLCMTypes")); end; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
